#ifndef ERROR_CODE_H
#define ERROR_CODE_H

typedef enum
{
    EC_SUCCESS = 0,
    EC_HELP_FLAG,
    EC_INVALID_ARGC,
    EC_INVALID_COMMAND,
    EC_INVALID_COMMAND_ARGC,
    EC_INVALID_DIRECTORY,
    EC_INVALID_SORTER,
    EC_SCANDIR_ERROR,
    EC_LIST_FEATURE,
    EC_INVALID_SEARCHED_NAME,
    EC_PARSE_ERROR,
    EC_PARSE_ERROR_SIZE,
    EC_MEMORY_ALLOCATION,
} ErrorCode;

#endif