#ifndef ERROR_CODE_H
#define ERROR_CODE_H

typedef enum
{
    EC_SUCCESS = 0,

    // Internal errors
    EC_HELP_FLAG,
    EC_CMD_HELP_FLAG,

    // System errors
    EC_INVALID_ARGC,
    EC_INVALID_COMMAND,
    EC_INVALID_COMMAND_ARGC,
    EC_INVALID_DIRECTORY,
    EC_INVALID_SORTER,
    EC_INVALID_SEARCHED_NAME,
    EC_SCANDIR_ERROR,
    EC_FOPEN_ERROR,
    EC_LIST_FEATURE_ERROR,    
    EC_PARSE_ERROR,
    EC_PARSE_ERROR_SIZE,
    EC_PARSE_ERROR_UNSUPPORTED,
    EC_MEMORY_ALLOCATION,
    EC_MISSING_BACKUP_MARKER
} ErrorCode;

#endif
