// Libraries
#include <stdio.h>

// Headers
#include "help.h"

// Prints 'help' command
void handle_help(void)
{
    puts(
        "Usage: ./archivist COMMAND [arguments]\n"
        "\n"
        "All commands:\n"
        "   backup      backs up files\n"
        "               Usage: ./archivist backup [DIRECTORY] DIRECTORY [FLAGS]\n"
        "\n"
        "   delete      deletes content from a directory\n"
        "               Usage: ./archivist delete [DIRECTORY] [FLAGS]\n"
        "\n"
        "   help        shows this help message\n"
        "               Usage: ./archivist help\n"
        "\n"
        "   list        lists contents of a directory\n"
        "               Usage: ./archivist list [DIRECTORY] [FLAGS]\n"
        "\n"
        "   log         displays log records\n"
        "               Usage: ./archivist log [FLAGS]\n"
        "\n"
        "   move        moves files and subdirectories\n"
        "               Usage: ./archivist move [DIRECTORY] DIRECTORY [FLAGS]\n"
        "\n"
        "   recover     recover files that were previously backed up\n"
        "               Usage: ./archivist recover [DIRECTORY] DIRECTORY [FLAGS]\n"
        "\n"
        "   rename      renames files\n"
        "               Usage: ./archivist rename [DIRECTORY] [FLAGS]\n"
        "\n"
        "   report      calculates percentage of each extension on a directory\n"
        "               Usage: ./archivist report [DIRECTORY] [FLAGS]\n"
        "\n"
        "   search      searches for an element (file, slink, directory)\n"
        "               Usage: ./archivist search [DIRECTORY] [FLAGS]\n"
        "\n"
        "   tree        displays the directory structure in a tree-like format\n"
        "               Usage: ./archivist tree [DIRECTORY]\n"
        "\n"
        "For more information about a specific command, use:\n"
        "   ./archivist COMMAND help\n"
        "Example:\n"
        "   ./archivist list help\n"
        "   ./archivist search help\n"
        "   ./archivist report help\n"
        "   ./archivist move help"
    );
}

// Prints explanation of 'backup' functionality
void print_backup_help(void)
{
    puts(
        "Usage: ./archivist backup [DIRECTORY] DIRECTORY [FLAGS]\n"
        "\n"
        "First DIRECTORY is the ORIGIN. It defaults to current directory (.)\n"
        "Second DIRECTORY is the DESTINATION. It is a required argument\n"
        "If destination directory doesn't exist, it will be created\n"
        "\n"
        "Flags:\n"
        "   -a | --all\n"
        "       includes hidden files and hidden directories\n"
        "       default: off\n"
        "   -A | --almost-all\n"
        "       includes hidden files, and filters hidden directories\n"
        "       default: off\n"
        "   -c | --contains\n"
        "       backs up only files that contain a word/pattern\n"
        "   -d | --dry-run\n"
        "       simulates changes, showing the result\n"
        "       default: off\n"
        "   -e | --extension\n"
        "       only backs up files of given extension\n"
        "       if more than 1 extension, separate them with a comma\n"
        "       e.g. .txt,\n"
        "   -i | --interactive\n"
        "       Asks for confirmation before backing up a file\n"
        "       default: off\n"
        "   -v | --verbose\n"
        "       states every backed up file\n"
        "       default: off\n"
        "   -R | --recursive\n"
        "       also makes backup of files in subdirectories\n"
        "       default: off\n"
        "   --min-size\n"
        "   --max-size\n"
        "       only consider files smaller/larger than specified value\n"
        "       notation: B | K | KB | M | MB | G | GB | T | TB\n"
        "       default: B (bytes)\n"
        "       e.g. 20 | 50K | 30GB | 200T\n"
        "\n"
        "Examples:\n"
        "   ./archivist backup /folder2\n"
        "   ./archivist backup /folder1 /folder2\n"
        "   ./archivist backup /folder1 /folder2 -c word --human-readable\n"
        "   ./archivist backup /folder1 /folder2 -d -e txt,pdf\n"
        "   ./archivist backup /folder1 /folder2 -i -v -R -a\n"
        "   ./archivist backup /folder1 /folder2 -A --min-size 50K --max-size 50G\n"        
        "\n"
        "All commands: ./archivist help"
    );
}

// Prints explanation of 'delete' functionality
void print_delete_help(void)
{
    puts(
        "Usage: ./archivist delete [DIRECTORY] [FLAGS]\n"
        "\n"
        "Directory defaults to current directory (.)\n"
        "\n"
        "Flags:\n"
        "   -a | --all\n"
        "       includes hidden files and hidden directories\n"
        "       default: off\n"
        "   -A | --almost-all\n"
        "       includes hidden files, and filters hidden directories\n"
        "       default: off\n"
        "   -c | --contains\n"
        "       deletes only files/subdirectories that contain a word/pattern\n"
        "   -d | --dry-run\n"
        "       simulates changes, showing the result\n"
        "       default: off\n"
        "   -e | --extension\n"
        "       deletes files of given extension\n"
        "       if more than 1 extension, separate them with a comma\n"
        "       e.g. txt | .txt\n"
        "   -h | --human-readable\n"
        "       outputs size of files/dir in a more readable format\n"
        "       default: off\n"
        "   -i | --interactive\n"
        "       Asks for confirmation before deleting file/directory\n"
        "       default: off\n"
        "   -t | --type\n"
        "       deletes only specific type (file | dir | slink)\n"
        "   -v | --verbose\n"
        "       states every deleted file/subdirectory\n"
        "       default: off\n"
        "   -R | --recursive\n"
        "       also deletes files in subdirectories\n"
        "       default: off\n"
        "   --min-size\n"
        "   --max-size\n"
        "       only consider files smaller/larger than specified value\n"
        "       notation: B | K | KB | M | MB | G | GB | T | TB\n"
        "       default: B (bytes)\n"
        "       e.g. 20 | 50K | 30GB | 200T\n"
        "\n"
        "Examples:\n"
        "   ./archivist delete\n"
        "   ./archivist delete /folder\n"
        "   ./archivist delete /folder -A -c word\n"
        "   ./archivist delete /folder -d -e txt,pdf\n"
        "   ./archivist delete /folder -i --type file\n"
        "   ./archivist delete /folder -v -R -a\n"
        "   ./archivist delete /folder -h --min-size 50K --max-size 50G\n"        
        "\n"
        "All commands: ./archivist help"
    );
}

// Prints explanation of 'list' functionality
void print_list_help(void)
{
    puts(
        "Usage: ./archivist list [DIRECTORY] [FLAGS]\n"
        "\n"
        "DIRECTORY defaults to current directory (.)\n"
        "\n"
        "Flags:\n"
        "   -a | --all\n"
        "       includes hidden files and hidden directories\n"
        "       default: off\n"
        "   -A | --almost-all\n"
        "       includes hidden files, and filters hidden directories\n"
        "       default: off\n"
        "   -h | --human-readable\n"
        "       outputs size of files/dir in a more readable format\n"
        "       default: off\n"
        "   -i | --ignore-case\n"
        "       distinguish case\n"
        "       default: off\n"
        "   -r | --reverse\n"
        "       changes order (ascending | descending)\n"
        "       default: off (ascending)\n"
        "   -s | --sort <date|name|size|extension|version>\n"
        "       sorts output by:\n"
        "           date → compares last modification date\n"
        "           name → compares the ASCII value of each character\n"
        "           size → compares the size of each file\n"
        "           extension → compares extension of each file\n"
        "           version → compares letters and numbers separately\n"
        "       default: name\n"
        "   -D | --dir-first\n"
        "       directories displayed before files\n"
        "       default: off\n"
        "   -R | --recursive\n"
        "       also lists subdirectories\n"
        "       default: off\n"
        "\n"
        "Examples:\n"
        "./archivist list\n"
        "./archivist list /folder\n"
        "./archivist list /folder -o size -R --all\n"
        "./archivist list /folder --dir-first --recursive --reverse\n"
        "./archivist list /folder --almost-all -h -i --sort version\n"
        "\n"
        "All commands: ./archivist help"
    );
}

// Prints explanation of 'log' functionality
void print_log_help(void)
{
    puts(
        "Usage: ./archivist log [FLAGS]\n"
        "Only for the following features: 'backup', 'delete', 'move', 'recover' and 'rename'\n"
        "There is no record for features: 'list', 'log', 'search', 'report' and 'tree'\n"
        "\n"
        "Flags:\n"
        "   -l | --limit\n"
        "       defines the number of ouput rows\n"
        "   -C | --command\n"
        "       filter the output by the specified command\n"
        "   -E | --erase\n"
        "       clears the .log file\n"
        "\n"
        "Examples:\n"
        "   ./archivist log\n"
        "   ./archivist log --command move\n"
        "   ./archivist log --limit 8\n"
        "\n"
        "All commands: ./archivist help"         
    );
}

// Prints explanation of 'move' functionality
void print_move_help(void)
{
    puts(
        "Usage: ./archivist move [DIRECTORY] DIRECTORY [FLAGS]\n"
        "\n"
        "First DIRECTORY is the ORIGIN. It defaults to current directory (.)\n"
        "Second DIRECTORY is the DESTINATION. It is a required argument\n"
        "If destination directory doesn't exist, it will be created\n"
        "If file already exists on destination, moved file will be incrementaly renamed (e.g. file.txt → file_2.txt)\n"
        "\n"
        "Flags:\n"
        "   -a | --all\n"
        "       includes hidden files and hidden directories\n"
        "       default: off\n"
        "   -A | --almost-all\n"
        "       includes hidden files, and filters hidden directories\n"
        "       default: off\n"
        "   -c | --contains\n"
        "       moves only files/subdirectories that contain a word/pattern\n"
        "   -d | --dry-run\n"
        "       simulates changes, showing the result\n"
        "       default: off\n"
        "   -e | --extension\n"
        "       move files of given extension\n"
        "       if more than 1 extension, separate them with a comma\n"
        "       e.g. txt | .txt\n"
        "   -f | --force\n"
        "       if file/subdirectory already exists, it will be overwritten\n"
        "       default: off\n"
        "   -i | --interactive\n"
        "       Asks for confirmation before moving file or creating directory\n"
        "       defaults: off\n"
        "   -s | --skip\n"
        "       if file/subdirectory alredy exists, it won't be moved\n"
        "       default: off\n"
        "   -t | --type\n"
        "       moves only specific type (file | dir | slink)\n"
        "   -v | --verbose\n"
        "       states every moved file/subdirectory\n"
        "       default: off\n"
        "   -R | --recursive\n"
        "       also moves files in subdirectories\n"
        "       default: off\n"
        "   --min-size\n"
        "   --max-size\n"
        "       only consider files smaller/larger than specified value\n"
        "       notation: B | K | KB | M | MB | G | GB | T | TB\n"
        "       default: B (bytes)\n"
        "       e.g. 20 | 50K | 30GB | 200T\n"
        "\n"
        "Attention:\n"
        "'force' and 'skip' flags are excludent. If both are provided, the last one will prevail\n"
        "\n"
        "Examples:\n"
        "   ./archivist move /folder2\n"
        "   ./archivist move /folder1 /folder2\n"
        "   ./archivist move /folder1 /folder2 -c word\n"
        "   ./archivist move /folder1 /folder2 -d -e txt,pdf\n"
        "   ./archivist move /folder1 /folder2 --force -i --type file\n"
        "   ./archivist move /folder1 /folder2 -s -v -R -a\n"
        "   ./archivist move /folder1 /folder2 -A --min-size 50K --max-size 50G\n"        
        "\n"
        "All commands: ./archivist help"
    );
}

// Prints explanation of 'recover' functionality
void print_recover_help(void)
{
    puts(
        "Usage: ./archivist recover [DIRECTORY] DIRECTORY [FLAGS]\n"
        "\n"
        "First DIRECTORY is the ORIGIN. It defaults to current directory (.)\n"
        "Second DIRECTORY is the DESTINATION. It is a required argument\n"
        "If destination directory doesn't exist, it will be created\n"
        "\n"
        "Flags:\n"
        "   -d | --dry-run\n"
        "       simulates changes, showing the result\n"
        "       default: off\n"
        "   -h | --human-readable\n"
        "       outputs size of backed up files in a more readable format\n"
        "       default: off\n"
        "   -i | --interactive\n"
        "       Asks for confirmation before backing up a file\n"
        "       default: off\n"
        "   -v | --verbose\n"
        "       states every backed up file\n"
        "       default: off\n"
        "\n"
        "Examples:\n"
        "   ./archivist recover /folder2\n"
        "   ./archivist recover /folder1 /folder2\n"
        "   ./archivist recover /folder1 /folder2 --human-readable\n"
        "   ./archivist recover /folder1 /folder2 -d\n"
        "   ./archivist recover /folder1 /folder2 -i -v\n"
        "\n"
        "All commands: ./archivist help"       
    );
}

// Prints explanation of 'rename' functionality
void print_rename_help(void)
{
    puts(
        "Usage: ./archivist rename [DIRECTORY] [FLAGS]\n"
        "\n"
        "Directory defaults to current directory (.)\n"
        "\n"
        "Flags:\n"
        "   -a | --all\n"
        "       includes hidden files and hidden directories\n"
        "       default: off\n"
        "   -A | --almost-all\n"
        "       includes hidden files, and filters hidden directories\n"
        "       default: off\n"
        "   -c | --contains\n"
        "       renames only files that contain a word/pattern\n"
        "   -d | --dry-run\n"
        "       simulates changes, showing the result\n"
        "       default: off\n"
        "   -e | --extension\n"
        "       renames files of given extension\n"
        "       if more than 1 extension, separate them with a comma\n"
        "       e.g. txt | .txt\n"
        "   -i | --interactive\n"
        "       Asks for confirmation before renaming a file\n"
        "       default: off\n"
        "   -n | --name\n"
        "       Defines the new name to be used to rename all files\n"
        "       default: file\n"
        "   -s | --sort <date|name|size|extension|version>\n"
        "       sorts output by:\n"
        "           date → compares last modification date\n"
        "           name → compares the ASCII value of each character\n"
        "           size → compares the size of each file\n"
        "           extension → compares extension of each file\n"
        "           version → compares letters and numbers separately\n"
        "       default: name\n"
        "   -v | --verbose\n"
        "       states every renamed file\n"
        "       default: off\n"
        "   -R | --recursive\n"
        "       also renames files in subdirectories\n"
        "       default: off\n"
        "   --min-size\n"
        "   --max-size\n"
        "       only consider files smaller/larger than specified value\n"
        "       notation: B | K | KB | M | MB | G | GB | T | TB\n"
        "       default: B (bytes)\n"
        "       e.g. 20 | 50K | 30GB | 200T\n"
        "\n"
        "Examples:\n"
        "   ./archivist rename\n"
        "   ./archivist rename /folder\n"
        "   ./archivist rename /folder -n new_name\n"
        "   ./archivist rename /folder --name new_name -c word -s size\n"
        "   ./archivist rename /folder -d -e txt,pdf\n"
        "   ./archivist rename /folder -i -v -R -a\n"
        "   ./archivist rename /folder -A -h --min-size 50K --max-size 50G\n"        
        "\n"
        "All commands: ./archivist help"
    );
}

// Prints explanation of 'report' functionality
void print_report_help(void)
{
    puts(
        "Usage: ./archivist report [DIRECTORY] [FLAGS]\n"
        "\n"
        "DIRECTORY defaults to current directory (.)\n"
        "\n"
        "Flags:\n"
        "   -a | --all\n"
        "       includes hidden files and hidden directories\n"
        "       default: off\n"
        "   -A | --almost-all\n"
        "       includes hidden files, and filters hidden directories\n"
        "       default: off\n"
        "   -e | --extension\n"
        "       displays information only of specified extensions\n"
        "       if more than 1 extension, separate them with a comma\n"
        "   -h | --human-readable\n"
        "       outputs size in a more readable format\n"
        "       default: off\n"
        "   -s | --sort <name | size | quantity>\n"
        "       sorts output by:\n"
        "           name → compares the ASCII value of each character\n"
        "           size → total size\n"
        "           quantity → number of files\n"
        "       default: name\n"
        "   -R | --recursive\n"
        "       also lists subdirectories\n"
        "       default: off\n"
        "\n"
        "Examples:\n"
        "   ./archivist report\n"
        "   ./archivist report /folder\n"
        "   ./archivist report /folder -e txt,pdf,jpeg\n"
        "   ./archivist report --human-readable --all\n"
        "   ./archivist report --almost-all -R\n"
        "\n"
        "All commands: ./archivist help"
    );
}

// Prints explanation of 'search' functionality
void print_search_help(void)
{
    puts(
        "Usage: ./archivist search [DIRECTORY] [FLAGS]\n"
        "\n"
        "DIRECTORY defaults to current directory (.)\n"
        "\n"
        "Flags:\n"
        "   -a | --all\n"
        "       includes hidden files and hidden directories\n"
        "       default: off\n"
        "   -A | --almost-all\n"
        "       includes hidden files, and filters hidden directories\n"
        "       default: off\n"
        "   -c | --contains\n"
        "       includes only files/directories that contain a word/pattern\n"
        "   -e | --extension\n"
        "       displays information only of specified extensions\n"
        "       if more than 1 extension, separate them with a comma\n"
        "   -t | --type\n"
        "       includes only specific type (file | dir | slink)\n"
        "   -R | --recursive\n"
        "       also search in subdirectories\n"
        "       default: off\n"
        "   --min-size\n"
        "   --max-size\n"
        "       only consider files smaller/larger than specified value\n"
        "       notation: B | K | KB | M | MB | G | GB | T | TB\n"
        "       default: B (bytes)\n"
        "       e.g. 20 | 50K | 30GB | 200T\n"
        "\n"
        "Examples:\n"        
        "./archivist search filename.txt\n"
        "./archivist search /folder -c filename.txt\n"
        "./archivist search /folder -e txt,pdf,jpeg \n"
        "./archivist search /folder -t file --all\n"
        "./archivist search /folder -A -R --min-size 50K --max-size 50G\n"
        "\n"
        "All comands: ./archivist help"
    );
}

// Prints explanation of 'tree' functionality
void print_tree_help(void)
{
    puts(
        "Usage: ./archivist tree [DIRECTORY]\n"
        "\n"
        "DIRECTORY defaults to current directory (.)\n"
        "\n"
        "Flags:\n"
        "   -a | --all\n"
        "       includes hidden files and hidden directories\n"
        "       default: off\n"
        "\n"
        "Examples:\n"
        "   ./archivist tree\n"
        "   ./archivist tree -a\n"
        "   ./archivist tree /folder\n"
        "\n"
        "All commands: ./archivist help"
    );
}
